version: '3.4'
services:
  social-v2.clothes.admin:
    image: social-v2.clothes.admin
    container_name: social-v2.clothes.admin
    build:
      context: ./clients/Social-v2.Clothes.Admin
      dockerfile: Dockerfile
    ports:
      - 3111:3000
    restart: always 

  social-v2.clothes.upload:
    image: social-v2.clothes.upload
    container_name: social-v2.clothes.upload
    build:
      context: ./services/Social-v2.Clothes.UploadMediaApi
      dockerfile: Dockerfile
    ports:
      - 3854:3854
    restart: always 

  social-v2.clothes.store-react:
    image: social-v2.clothes.store-react
    container_name: social-v2.clothes.store-react
    build:
      context: ./clients/Social-v2.Clothes.Store
      dockerfile: Dockerfile
    ports:
      - 1611:80
    restart: always 

  social-v2.clothes.api-debug:
    image: social-v2.clothes.api-debug
    container_name: social-v2.clothes.api-debug
    build:
      context: ./services/Social-v2.Clothes.Api
      dockerfile: Social-v2.Clothes.Api/Dockerfile-debug
    ports:
      - 3954:80
    restart: always 
  
  social-v2.clothes.api-production:
    image: social-v2.clothes.api-production
    container_name: social-v2.clothes.api-production
    build:
      context: ./services/Social-v2.Clothes.Api
      dockerfile: Social-v2.Clothes.Api/Dockerfile
    ports:
      - 3954:80
    restart: always 
