#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 3954

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Social-v2.Clothes.Api/Social-v2.Clothes.Api.csproj", "Social-v2.Clothes.Api/"]
RUN dotnet restore "Social-v2.Clothes.Api/Social-v2.Clothes.Api.csproj"
COPY . .
WORKDIR "/src/Social-v2.Clothes.Api"
RUN dotnet build "Social-v2.Clothes.Api.csproj" -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish "Social-v2.Clothes.Api.csproj" -c Debug -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Social-v2.Clothes.Api.dll"]